* MEMBRES
** ALI Djamel (0769668162), djamel.ali1920@gmail.com
** IDRISSOU Hamza (0666811649), idrissouhamza044@gmail.com
* 3/11/2020
*** RDV mardi 10 devant Sophie Germain pour prendre le robot
* 18/11/2020
** FAIT :
*** OS installé
*** Hello World foncionne
** À faire :
*** tourner le moteur
*** utiliser le capteur RGB
*** réfléchir à un algo de reconnaissance de couleurs
* 02/12/2020
** À faire :
*** Il faut utiliser la bonne bibliothèque ('ev3dev' au lieu de 'lejos') pour tourner le moteur
*** Capter un triplet RGB avec le capteur de couleurs
*** Apprentissage de couleurs : savoir distinguer le fond de la ligne
* 09/12/2020
** Fait :
*** La brique commande deux moteurs qui peuvent bouger à des vitesses différentes et dans les 2 sens.
*** Récupérer les valeurs RGB en pointant le capteur sur une couleur.
*** Début de la partie 'Apprentissage' (pas encore terminée).
** À faire :
*** Terminer l'algorithme d'apprentissage.
*** Faire des tests (de reconnaissance basés sur ce qui a été appris dans la phase d'apprentissage).
*** Faire une liste des pièces manquantes (c.f. ./pieces_manquantes_ou_defectueuse.zip).
*** Aller récupérer les pièces manquantes Mercredi 16/12/2020 à 11:00 à Sophie Germain.
* 27/01/2021
** Fait :
*** Algorithme d'apprentissage (branche develop).
*** Remonter le robot en ajoutant les pièces manquantes.
** À faire :
*** Faire des tests (de reconnaissance basés sur ce qui a été appris dans la phase d'apprentissage) sur des lignes droites.
*** Suivre une ligne droite.
* 10/02/2021
** Fait :
*** Algorithme d'apprentissage (version finale dans la branche master)
*** Suivre une ligne droite.
*** Des testes ont été faits (testes de reconnaissance basés sur ce qui a été appris dans la phase d'apprentissage) sur des lignes droites.
** À faire :
*** Suivre des lignes courbes.
*** Faire des tests (de reconnaissance basés sur ce qui a été appris dans la phase d'apprentissage) sur des lignes courbes.
* 24/02/2021
** Fait :
*** Suivre des lignes courbes (trop lent et n'arrive pas à bien suivre les virages ayant un angle d'environ 90° et plus); (c.f branche develop)
*** Tester si l'exception générée lors de l'initialisation des moteurs vient du matériel (moteurs, câbles, brique) ou bien du logiciel (finalement, ce n'est pas un problème matériel).
** À faire :
*** Améliorer l'algorithme du suiveur de lignes courbes (vitesse + précision) et finir l'algorithme PID déjà commencé.
*** Réinstaller ev3dev et voir si l'exception liée à l'initialisation des moteurs (générée en moyenne 1 fois sur 2) persiste encore ou pas.
*** Faire des tests sur diverses lignes courbes.
* 03/03/2021
** Fait :
*** Réinstallation de l'OS (leJOS EV3 au lieu de ev3dev) (exception liée à l'initialisation des moteurs réglée).
*** Petite modification dans le montage du robot (la roue arrière tourne maintenant dans le bon sens dans les virages au lieu de glisser).
** À faire :
*** Adapter tout le code du projet pour qu'il fonctionne sous LeJos (au lieu de ev3dev), et le migrer de l'IDE IntelliJ IDEA à Eclipse (qui utilise un plugin LeJos contrairement aux autres IDEs).
*** Améliorer l'algorithme du suiveur de lignes courbes (vitesse + précision) et finir l'algorithme PID déjà commencé.
*** Faire des tests sur diverses lignes courbes.
* 31/03/2021
** Fait :
*** Adaptation du code du programme pour qu'il fonctionne sous LeJos (au lieu de ev3dev).
*** (Migration du programme et de tout le projet de l'IDE IntelliJ IDEA à Eclipse.)
*** Programme PID terminé.
*** Modification dans la manière de monter le capteur sur du robot (il est à une meilleure distance du sol maintenant, donc une meilleure précision lorsqu'il suit la ligne).
*** Plusieurs tests sur des lignes courbes ont été faits afin de trouver une bonne première estimation de la série de paramètres kp, ki et kd.
** À faire :
*** Continuer à faire plusieurs tests sur diverses types de lignes, des virages un peu plus serrés, des intersections aux couleurs différentes.
*** Ajouter l'option "trouver la ligne" dans le cas ou le robot se perd à un moment donné dans le fond.
*** (S'il reste du temps, fair une sorte de "mémorisation" au premier tour afin de suivre la ligne intelligemment au 2nd tour et plus).
* 07/04/2021
** Fait :
*** Plusieurs tests sur diverses types de lignes, des virages un peu plus serrés, des intersections aux couleurs différentes (si la couleur de l'intersection est assez proche de la couleur de la ligne il risque de la suivre)
*** Ajout de l'option "trouver la ligne" en tournant en spiral (pas entièrement finie, elle est encore en cours de développement dans la branche 'look_for_line', il reste à ajuster les valeurs pour faire des formes spirales parfaites).
** À Faire :
*** Enregistrer une vidéo (et des photos s'il le faut) pour montrer tout ce que peut faire le robot (ses caractéristiques et comportements...).
*** Perfectionner le mouvement en spiral afin de trouver/retrouver la ligne.
*** Essayer d'améliorer la vitesse (particulièrement sur les lignes droites).
* 14/04/2021
** Fait :
*** Enregistrement de vidéos (liens : PID Algorithm => https://www.youtube.com/watch?v=FhZJFoExKqs , PI Algorithm => https://www.youtube.com/watch?v=XVTuLtFHmvY).
*** Vitesse améliorée (mais toujours en train d'essayer d'en faire mieux).
** À Faire :
*** Mémoriser la couleur de ligne de départ/arrivé pour s'arrêter une fois le tour est fait.
*** Rédiger le rapport de ce projet.
* 14/04/2021
** Fait :
*** Mémoriser la couleur de ligne de départ/arrivé pour s'arrêter une fois le tour est fait.
*** Rédiger le rapport final de ce projet.
