* MEMBRES
** ALI Djamel (0769668162), djamel.ali1920@gmail.com
** IDRISSOU Hamza (0666811649), idrissouhamza044@gmail.com
* 3/11/2020
*** RDV mardi 10 devant Sophie Germain pour prendre le robot
* 18/11/2020
** FAIT :
*** OS installé
*** Hello World foncionne
** À faire :
*** tourner le moteur
*** utiliser le capteur RGB
*** réfléchir à un algo de reconnaissance de couleurs
* 02/12/2020
** À faire :
*** Il faut utiliser la bonne bibliothèque ('ev3dev' au lieu de 'lejos') pour tourner le moteur
*** Capter un triplet RGB avec le capteur de couleurs
*** Apprentissage de couleurs : savoir distinguer le fond de la ligne
* 09/12/2020
** Fait :
*** La brique commande deux moteurs qui peuvent bouger à des vitesses différentes et dans les 2 sens.
*** Récupérer les valeurs RGB en pointant le capteur sur une couleur.
*** Début de la partie 'Apprentissage' (pas encore terminée).
** À faire :
*** Terminer l'algorithme d'apprentissage.
*** Faire des tests (de reconnaissance basé sur ce qui a été appris dans la phase d'apprentissage).
*** Faire une liste des pièces manquantes (c.f. ./pieces_manquantes_ou_defectueuse.zip).
*** Aller récupérer les pièces manquantes Mercredi 16/12/2020 à 11:00 à Sophie Germain.
* 27/01/2021
** Fait :
*** Algorithme d'apprentissage (branche develop).
*** Remonter le robot en ajoutant les pièces manquantes.
** À faire :
*** Faire des tests (de reconnaissance basé sur ce qui a été appris dans la phase d'apprentissage) sur des lignes droites.
*** Suivre une ligne droite.
* 10/02/2021
** Fait :
*** Algorithme d'apprentissage (version finale dans la branche master)
*** Suivre une ligne droite.
*** Des testes ont été faits (testes de reconnaissance basé sur ce qui a été appris dans la phase d'apprentissage) sur des lignes droites.
** À faire :
*** Suivre des lignes courbes.
*** Faire des tests (de reconnaissance basé sur ce qui a été appris dans la phase d'apprentissage) sur des lignes courbes.
* 24/02/2021
** Fait :
*** Suivre des lignes courbes (trop lent et n'arrive pas à bien suivre les virages ayant un angle d'environ 90° et plus); (c.f branche develop)
*** Tester si l'exception générée lors de l'initialisation des moteurs vient du matériel (moteurs, câbles, brique) ou bien du logiciel (finalement, ce n'est pas un problème matériel).
** À faire :
*** Améliorer l'algorithme du suiveur de lignes courbes (vitesse + précision) et finir l'algorithme PID déjà commencé.
*** Réinstaller ev3dev et voir si l'exception liée à l'initialisation des moteurs (générée en moyenne 1 fois sur 2) persiste encore ou pas.
*** Faire des tests sur diverses lignes courbes.